project:
  type: book

execute:
  freeze: auto
  # echo: false
  warning: false

book:
  title: "A journey through aviation data"
  favicon: "favicon.png"
  author: "Xavier Olive, Junzi Sun, Enrico Spinielli, Manuel Waltert"
  date: "2023-12-25"
  chapters:
    - index.qmd
    - 01-preface.qmd
    - 02-toc.qmd
    - part: "Background knowledge about aviation"
      chapters:
        - 11-history.qmd
        - 12-aircraft.qmd
        - 13-earth.qmd
        - 14-airspace.qmd
        - 15-aerodrome.qmd
        - 16-cns.qmd
    - part: "The ecosystem of aviation data"
      chapters:
        - 21-trajectories.qmd
        - 22-aeronautical-information.qmd
        - 23-environment.qmd
        - 24-aircraft-performance.qmd
        - 25-aviation-data-sources.qmd
    - part: "Process data"
      chapters:
        - 31-tidy-data.qmd
        - 32-geometrice-geographic.qmd
        - 33-processing-trajectories.qmd
        - 34-information-extraction.qmd
    - part: "Visualise Data"
      chapters:
        - 41-storytelling.qmd
        - 42-grammar-of-graphics.qmd
        - 43-meaningful-maps.qmd
    - part: "Share Data"
      chapters:
        - 51-reproducible-research.qmd
    - 90-references.qmd
    - 91-authors.qmd
  appendices:
    - 71-appendix.qmd
    - 88-acronyms.qmd

  # cover-image: images/book-front-cover.png
  site-url: https://aviationbook.netlify.app/
  repo-url: https://github.com/atmdata/aviationbook/
  repo-branch: master

  search: true
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]

  page-navigation: true

  # comments:
  #   hypothesis: true

  sidebar:
    - title: Background
      id: introduction
      background: transparent
      collapse-level: 1
      contents:
        - text: Background knowledge about aviation
        - text: ---
        - 11-history.qmd
        - 12-aircraft.qmd
        - 13-earth.qmd
        - 14-airspace.qmd
        - 15-aerodrome.qmd
        - 16-cns.qmd
    - title: Data sources
      id: data_sources
      background: transparent
      contents:
        - text: The ecosystem of aviation data
        - text: ---
        - 21-trajectories.qmd
        - 22-aeronautical-information.qmd
        - 23-environment.qmd
        - 24-aircraft-performance.qmd
        - 25-aviation-data-sources.qmd
    - title: Processing data
      id: data_process
      background: transparent
      contents:
        - text: Processing data
        - text: ---
        - 31-tidy-data.qmd
        - 32-geometrice-geographic.qmd
        - 33-processing-trajectories.qmd
        - 34-information-extraction.qmd
    - title: Visualizing data
      background: transparent
      id: dataviz
      contents:
        - text: Visualizing data
        - text: ---
        - 41-storytelling.qmd
        - 42-grammar-of-graphics.qmd
        - 43-meaningful-maps.qmd
    - title: Sharing data
      id: data_share
      background: transparent
      contents:
        - text: Sharing & reproducibility
        - text: ---
        - 51-reproducible-research.qmd

  navbar:
    background: light
    logo: favicon.png
    logo-alt: "avbook logo"
    title: false
    search: true
    pinned: true
    left:
      - sidebar:introduction
      - sidebar:data_sources
      - sidebar:data_process
      - sidebar:dataviz
      - sidebar:data_share
    right: []

crossref:
  fig-title: Figure
  tbl-title: Table
  fig-prefix: Figure
  tbl-prefix: Table
  ref-hyperlink: true
  #   appendix-title: "App."
  #   appendix-delim: ":"

bibliography: bibliography.bib
csl: media/ieee.csl

# for debug
# geometry:
#   - showframe

pdf-engine: xelatex

highlight-style: pygments

format:
  html:
    theme:
      light: [flatly, media/css/light.scss]
      dark: [darkly, media/css/dark.scss]
    smooth-scroll: true
    toc: true
    code-copy: true
    css:
      - media/css/style.css
      - media/css/box.css
    grid:
      sidebar-width: 400px
      body-width: 900px
      margin-width: 300px
  pdf:
    documentclass: scrbook
    papersize: a4
